# Generated by Django 3.1 on 2020-08-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooshak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز', 'verbose_name_plural': 'سایز'},
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=5, verbose_name='تعریف سایز'),
        ),
    ]
