# Generated by Django 3.1 on 2020-08-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooshak', '0002_auto_20200813_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportset',
            name='kolah',
            field=models.IntegerField(choices=[('1', 'بدون کلاه'), ('2', 'کلاهدار')], verbose_name='کلاه'),
        ),
    ]
