# Generated by Django 3.1 on 2020-08-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooshak', '0003_auto_20200813_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportset',
            name='kolah',
            field=models.CharField(choices=[('K', 'بدون کلاه'), ('BK', 'کلاهدار')], max_length=2, verbose_name='کلاه'),
        ),
    ]
