# Generated by Django 3.1 on 2020-08-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooshak', '0004_auto_20200813_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportset',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
