# Generated by Django 3.1 on 2020-08-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooshak', '0005_sportset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportset',
            name='pic1',
            field=models.ImageField(blank=True, upload_to='SportSet', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='sportset',
            name='pic2',
            field=models.ImageField(blank=True, upload_to='SportSet', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='sportset',
            name='pic3',
            field=models.ImageField(blank=True, upload_to='SportSet', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='sportset',
            name='pic4',
            field=models.ImageField(blank=True, upload_to='SportSet', verbose_name='تصویر'),
        ),
    ]
