# Generated by Django 3.1 on 2020-08-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooshak', '0006_auto_20200819_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportset',
            name='form',
            field=models.CharField(choices=[('معمولی', 'معمولی'), ('آزاد', 'آزاد')], max_length=6, verbose_name='فرم لباس'),
        ),
        migrations.AlterField(
            model_name='sportset',
            name='kolah',
            field=models.CharField(choices=[('بدون کلاه', 'بدون کلاه'), ('کلاهدار', 'کلاهدار')], max_length=9, verbose_name='کلاه'),
        ),
        migrations.AlterField(
            model_name='sportset',
            name='tarh',
            field=models.CharField(choices=[('ساده', 'ساده'), ('طرح دار', 'طرح دار')], max_length=7, verbose_name='طرح پارچه'),
        ),
    ]
